### ISSUE TITLE
session/line number not unique error, reproducible example

### ISSUE THREAD

**Issue by ssh352** [jalvesaq/vimcmdline#100]
I have encountered this error via a simple example. Could anyone advise?

<img width="856" alt="Screen Shot 2022-05-09 at 10 35 35 AM" src="https://user-images.githubusercontent.com/41779116/167337152-f98ad4b6-a3c1-42fd-b156-d8c09e555b48.png">

neovim 0.7.0
python 3.9.12
ipython  8.3.0
vimcmdline latest

**Comment by jalvesaq** [comment]
Could you try Python instead of iPython, please?

**Comment by ssh352** [comment]
> 

Thanks for the advice. no such problem with python. Wish I could still use ipython without such problem.

**Comment by jalvesaq** [comment]
People who have contributed to support iPython were @epwalsh, @kprimice and @ianliu.

**Comment by smilesun** [comment]
same issue with ipython on my side with the current commit, but if I remember correctly, ipython works before the Feburary commit.

**Comment by jalvesaq** [comment]
I installed `ipython`, sent a few lines to it, and couldn't see any issues...

**Comment by ssh352** [comment]
it works with latest neovim and ipython. ipython must have fixed it. closing.
