### ISSUE TITLE
117: Unknown function: VimCmdLineSendCmd

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/vimcmdline#102]
117: Unknown function: VimCmdLineSendCmd

I have the following definition in my vim script
`858:autocmd FileType python nmap <buffer> <LocalLeader>pp :call VimCmdLineSendCmd(expand('<cword>'))<CR>`

**Comment by jalvesaq** [comment]
Please try:

```vim
autocmd FileType python nmap <buffer> <LocalLeader>pp :call cmdline#SendCmd(expand('<cword>'))<CR>
```

**Comment by smilesun** [comment]
it works!
