### ISSUE TITLE
new feature: execute up to the current line

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/vimcmdline#103]
`autocmd FileType python nmap <buffer> <LocalLeader>pp :call cmdline#SendCmd(expand('<cword>'))<CR>
`
will print the current variable value,

leader + f will run the whole file, 

is it possible to run the file only until cusor?

**Comment by jalvesaq** [comment]
You may try this:

```vim
autocmd FileType python nmap <buffer> <LocalLeader>uh :call b:cmdline_source_fun(getline(1, line('.')))<CR>
```

**Comment by smilesun** [comment]
it works !
