### ISSUE TITLE
Hy support?

### ISSUE THREAD

**Issue by bsturk** [jalvesaq/vimcmdline#105]
Great plugin, works amazing with python for me!

Any chance support for "hy-lang" could be added?  I made the cmdline_app map and set ['hy'] to 'hy', but nothing happens.  I'm assuming this is due to not having support built in?

**Comment by jalvesaq** [comment]
The README has instructions on how to add support for a language. It's very simple. Please, do a pull request...

**Comment by bsturk** [comment]
Ok, will do

**Comment by bsturk** [comment]
Done, if including the syntax file I did is not acceptable, please let me know.
