### ISSUE TITLE
Indentation is lost (ipython)

### ISSUE THREAD

**Issue by kprimice** [jalvesaq/vimcmdline#18]
Hi,

Thank you for this plugin, I am already an heavy Nvim-R user. Wanted to try this one for python.

My problem is when I try to send this code:
![2017-03-09-07 49 39](https://cloud.githubusercontent.com/assets/7632903/23738997/8dfd253e-049c-11e7-8b7b-3a2b0118d1de.png)

It fails because of the indentation:
![2017-03-09-07 49 46](https://cloud.githubusercontent.com/assets/7632903/23739016/a058e2a4-049c-11e7-970a-11801b24bc7a.png)

I tried to use an external terminal (with tmux) or the nvim buffer. But it fails everytime.

Thank you for you help

**Comment by jalvesaq** [comment]
Perhaps this is a problem with 'expandtab'. Did you set this option in your vimrc? Anyway, some people have reported incompatibility between vimcmdline and `ipython`.

**Comment by kprimice** [comment]
Yes, here are the options I use:

`au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix
`

I just checked: Indeed it is an ipython related bug.

**Comment by jalvesaq** [comment]
Thanks for the feedback. I am going to add a warning when `cmdline_app["python"]` value is `"ipython"`.

**Comment by jalvesaq** [comment]
The solution for the indentation issue is:
```vim
let g:cmdline_app = {"python": "ipython --no-autoindent"}
```

But I noted other issues:

  - ipython starts in a state similar to Vim's Normal mode, and I have to press either `i` or `a` to go to insert mode before sending lines from Neovim to ipython.
  - Neovim terminal does not auto scroll when lines are sent.

**Comment by smilesun** [comment]
@jalvesaq , when I set this cmdline_app, I got 

```
Error detected while processing function VimCmdLineStartApp[18]..VimCmdLineStart_Tmux:                                                    
line   23:                                                                                                                                
E121: Undefined variable: usage                                                                                                           
E15: Invalid expression: usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]^@
```

**Comment by jalvesaq** [comment]
@kprimice is the author of https://github.com/jalvesaq/vimcmdline/pull/27

**Comment by smilesun** [comment]
well, even if I delete the definition of cmdline_app, there is no complain from vim side, but still, the indentation is wrong when I leader+space a python function

**Comment by smilesun** [comment]
I am using python-mode/pythonmode and vim-scripts/indentpython.vim
