### ISSUE TITLE
when opening a javascript with `vim-jsx` installed I get an error

### ISSUE THREAD

**Issue by sodiumjoe** [jalvesaq/vimcmdline#19]
```bash
$ vim foo.js
```

```
"foo.js" [New File]
Error detected while processing function VimCmdLineSetApp:
line    8:
E716: Key not present in Dictionary: javascript.jsx
E15: Invalid expression: g:cmdline_job[&filetype] || g:cmdline_tmuxsname[&filetype] != "" || s:cmdline_app_pane != ''
```

I believe that comes from https://github.com/mxw/vim-jsx/blob/master/ftdetect/javascript.vim#L34

It seems like `vimcmdline` should just ignore unknown filetypes?

**Comment by jalvesaq** [comment]
When the filetype is `javascript.jsx`, Vim calls `ftplugin/javascript_*.vim`. What application should be run to interpret javascript.jsx code? Is it node? If yes, could you please replace the last line of `ftplugin/javascript_cmdline.vim` with:
```
call VimCmdLineSetApp(&filetype)
```
Does it work now? Can you start the application (which is `node` by default) and run lines of your code?

**Comment by jalvesaq** [comment]
If `javascript` and `javascript.jsx` do not use the same interpreter to evaluate lines, then, the following line should be put at the top of `ftplugin/javascript_cmdline.vim`:
```vim
if &filetype != "javascript"
   finish
endif
```
Since I don't use javascript, either you or @chee have to tell me what to do.

**Comment by sodiumjoe** [comment]
I tried `call VimCmdLineSetApp(&filetype)`, which does not appear to have any effect. I still get the same error when opening a javascript file.

It's actually kind of tricky with "modern" javascript (and jsx) because it has to run through a compiler. The easiest solution I can come up with is:

```vim
let g:cmdline_app = {}
let g:cmdline_app['javascript'] = 'babel-node'
```

but it depends on having `babel-cli` installed globally, and being in a project with a working babel config.

Everything appears to work fine, including jsx, except for the error.

**Comment by jalvesaq** [comment]
I committed some changes. Is it OK now?

**Comment by sodiumjoe** [comment]
`jsx` syntax doesn't appear to work, but I no longer see the error and regular javascript appears to work fine. Good enough for me. Thanks!
