### ISSUE TITLE
colorize output in tmux pane 

### ISSUE THREAD

**Issue by bsabri** [jalvesaq/vimcmdline#20]
I'm using the following command in .vimrc to run a terminal in tmux pane:
let cmdline_external_term_cmd = "tmux split-window '%s'"

Is it possible to colorize for example python output (using vimcmdline
) in a tmux pane similar to nvim-R tmux pane ?

**Comment by jalvesaq** [comment]
The output of R is colorized in a Tmux pane by the package [colorout](https://github.com/jalvesaq/colorout). Nvim-R can colorize R output only if R is running in a built-in Neovim terminal emulator.

I don't know Python well enough to answer your question. The package colorout replaces R's function that does the output, and perhaps a Python library could do the same.

I suggest that you use Neovim.
