### ISSUE TITLE
ipython: only first line is sent

### ISSUE THREAD

**Issue by kprimice** [jalvesaq/vimcmdline#26]
This issue occurs only with ipython.

When I select multiple lines with shift + v and send them to the Terminal with < space >, only the first line is pasted and executed.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug!
I am going to remove support for ipython until someone does a pull request that fixes all problems.

**Comment by kprimice** [comment]
So I found the "problem".

I submitted another issue related to indentation  #18 where you suggested to use:

`let g:cmdline_app = {"python": "ipython --no-autoindent"}`

Which is actually the cause of this "multiple line selection" problem. So I reverted to:

`let g:cmdline_app = {"python": "ipython"}`

As for the issue #18, I still have it. But if I use the shift + v to paste the whole Class then it works just fine.

**Comment by jalvesaq** [comment]
@kprimice could you do a pull request for this, please?

**Comment by kprimice** [comment]
@jalvesaq I didn't change the code, I used the previous commit (3e9de45cd)

**Comment by jalvesaq** [comment]
I am sorry, but I will not bring back support for ipython unless someone does a pull request changing what has to be changed.

**Comment by smilesun** [comment]
@jalvesaq , sorry it was my own mistake.  

- For if else, afterwards there should be an empty line
- The same empty line should be set after a function definition
- do not use reserved words in function definition.
