### ISSUE TITLE
Support for Scala REPL?

### ISSUE THREAD

**Issue by kropper** [jalvesaq/vimcmdline#28]
While adding new supported languages/REPLs is known not to be a priority, are there any chances you could add support for the Scala REPL? (`scala` or `amm`) 

The Scala REPLs have multi-line output, which is not handled that great by similar vim/nvim plug-ins, but as _vimcmdline_ already supports Shells, it might be easier to add here?

**Comment by jalvesaq** [comment]
I will not support other languages, but I accept pull requests adding support for them. It's easy. Just choose the most similar language already supported, copy the files from the ftplugin and syntax directories and make the necessary adjustments.

**Comment by gnebbia** [comment]
I just added a pull request for the Scala language

**Comment by jalvesaq** [comment]
@gnebbia Why did you close the pull request?

**Comment by gnebbia** [comment]
i think by mistake...

**Comment by gnebbia** [comment]
Sorry Sir, by mistake I deleted the branches after merging on my master, anyway I'll create a new branch and i'll make a new pull request, Just give me a minute.
