### ISSUE TITLE
Launch inside docker container

### ISSUE THREAD

**Issue by kprimice** [jalvesaq/vimcmdline#29]
I am a huge fan of docker, and I'd like to use vimcmdline to debug my scripts that are running inside a container.

It is actually simple to change init.vim to make it work:
`let cmdline_app["python"] = "docker exec -it container /usr/python3"`

But I don't want to have to edit my config file every time I want to attach to a different container. What would you suggest? I am willing to do a pull request.

Could we imagine a new shortcut? That would query the user for a custom command line?

**Comment by jalvesaq** [comment]
What about putting this in your vimrc:
```vim
function StartDocker()
    let bclapp = b:cmdline_app
    if &filetype == "python"
        let b:cmdline_app = "docker exec -it container /usr/python3"
    elseif &filetype == "ruby"
        let b:cmdline_app = "docker exec -it container /usr/irb"
    endif
    call VimCmdLineStartApp()
    let b:cmdline_app = bclapp
endfunction

nmap <LocalLeader>d :call StartDocker()<CR>
```
Of course you have to add as many `elseif &filetype == "language"` as are the languages that you want to run in docker.

**Comment by kprimice** [comment]
Interesting solution! Would it be possible to customize the container name?

Let's say I have two containers "container1" and "container2" where I want to run python. I'd like to be able to choose between 

> docker exec -it container1 /usr/python3

and

> docker exec -it container2 /usr/python3

One way I can think of would be to prompt the user for the container name.

**Comment by kprimice** [comment]
I found the solution:

`  let curline = getline('.')
  call inputsave()
  let name = input('Enter name: ')
  call inputrestore()
  call setline('.', curline . ' ' . name)`

**Comment by kprimice** [comment]
I found a solution:

```vim
function StartDocker()
    let bclapp = b:cmdline_app
    if &filetype == "python"
	call inputsave()
	let container = input('Enter container name: ')
	call inputrestore()
        let b:cmdline_app = "docker exec -it " . container . " /usr/bin/python3"
    elseif &filetype == "ruby"
        let b:cmdline_app = "docker exec -it container /usr/irb"
    endif
    call VimCmdLineStartApp()
    let b:cmdline_app = bclapp
endfunction

nmap <LocalLeader>d :call StartDocker()<CR>
```

**Comment by jalvesaq** [comment]
If you will only use Python, it is OK to put the input commands inside the "python" condition. Otherwise it would be better to put the three lines above the first condition:

```vim
function StartDocker()
    let bclapp = b:cmdline_app
    call inputsave()
    let container = input('Enter container name: ')
    call inputrestore()
    if &filetype == "python"
        let b:cmdline_app = "docker exec -it " . container . " /usr/bin/python3"
    elseif &filetype == "ruby"
        let b:cmdline_app = "docker exec -it " . container . " /usr/irb"
    endif
    call VimCmdLineStartApp()
    let b:cmdline_app = bclapp
endfunction

nmap <LocalLeader>d :call StartDocker()<CR>
```
