### ISSUE TITLE
execute the whole python class

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/vimcmdline#39]
Hi, what should I do if I do not want to use space to execute each line of a python class but instead the whole class?

**Comment by jalvesaq** [comment]
You have to manually select the whole class and send the selection to Python.

**Comment by smilesun** [comment]
I did that, but what if the class is very big?

**Comment by jalvesaq** [comment]
I'm sorry, but vimcmdline is a general tool. Someone would have to fork it to add features specifically tailored to Python. I'm not going to do this because I use Python only rarely.

**Comment by jalvesaq** [comment]
I had to write code in Python last week... Could you, please, check if it is ok now?

**Comment by smilesun** [comment]
Hi, It works good on my computer, thjanks for the efforts!

**Comment by jdearmas** [comment]
Is there anything that needs to be done to set this option into effect? 

If I visually select a class and call PythonSendLines(), it works.

But it doesn't seem to map to cmdline_send; visually selecting the whole class and hitting the key-bindings for cmdline_send produces an indentation error.

**Comment by smilesun** [comment]
@jdearmas , it works on myside,  try `let cmdline_app['python'] = '~/anaconda3/bin/ipython --no-autoindent'`

**Comment by jalvesaq** [comment]
The whole `if`/`while` statement is also being sent as a whole when sending lines if it is at the beginning of the line.
