### ISSUE TITLE
vimcmdline sending an extra newline to Julia REPL from neovim

### ISSUE THREAD

**Issue by dm319** [jalvesaq/vimcmdline#40]
Hi there, I'm having a small problem with using vimcmdline with Julia.  I'm currently on an UbuntuMATE 18.04 system which is currently fully updated.  Running NVIM v0.3.0-dev in MATE Terminal 1.20. With a blank .vimrc file and only the vimcmdline and julia-vim plugin's installed, using space to send a line to the REPL results in what looks like two newlines being sent.

This is the result of pressing the spacebar twice:

![screenshot at 2018-05-23 20-37-25](https://user-images.githubusercontent.com/16006536/40447058-38d9496a-5ec9-11e8-920e-ebc01f62b485.png)

I can't remove julia-vim plugin because nvim doesn't seem to recognise the .jl as a julia file, which stops me opening the REPL.

Happy to provide / do further info or tests to try to pin this down.  I've only discovered this plugin today and enjoying it so far (the extra newline doesn't seem to cause too many problems).  TIA.

**Comment by jalvesaq** [comment]
I'm sorry, but I don't use Julia, and don't have it installed. Perhaps someone else can help fixing this issue, but looking at `ftplugin/julia_cmdline.vim` we can see:
```vim
let b:cmdline_nl = "\r\n"
```
You could try changing it to either `"\n"` or `"\r"`. However, it would be better to test the change on different platforms (Windows, Linux, Mac OS X).

If you look at /usr/local/share/nvim/runtime/filetype.vim, you will see that .jl is associated with lisp. So, you could put in your vimrc:
```vim
autocmd BufNewFile,BufRead *.jl set ft=julia
```

**Comment by dm319** [comment]
Ah, yes that fixes it!

    let b:cmdline_nl = "\n"

is a solution on my linux system, though I'm aware that '\n' is the unix line-ending.  I think '\r\n' is a Windows line-ending?

I don't seem to have this problem with your other excellent plug-in nvim-R.

Also thanks for pointing out language issue.  julia-vim must do this implicitly, so I'll leave it on.

**Comment by jalvesaq** [comment]
I use R frequently, and sometimes I test Nvim-R on Windows.
I will change the newline to `\n` unless Vim/Neovim is running on Windows. I will change it on Windows too if someone reports an issue.
Thanks!

**Comment by dm319** [comment]
Brilliant thanks!  This plugin has made Julia far more pleasant to use.  I'm also a heavy R user, so it's nice to be able to use Julia in the way I use R (mostly!).  Thanks again.

**Comment by adrianadermon** [comment]
I have the same issue on Windows - setting the newline character to just "\n" works correctly.

**Comment by jalvesaq** [comment]
I changed it to `"\n"`.
