### ISSUE TITLE
Line sent to Python REPL on Windows is not evaluated

### ISSUE THREAD

**Issue by adrianadermon** [jalvesaq/vimcmdline#42]
When I send a line to the Python REPL (either plain python or ipython), the contents of the line is entered in the REPL, but they are not evaluated. In order to execute the command I have to go to the REPL and hit Enter.

This issue does not arise with the Julia REPL, which works as expected. 

I'm using Neovim 0.3 on Windows 10.

**Comment by jalvesaq** [comment]
The new line for Julia is `\r\n` on Windows and `\n` on other systems:
https://github.com/jalvesaq/vimcmdline/blob/master/ftplugin/julia_cmdline.vim#L11-L15
Could you try the same with Python to see if the change fix the issue? I don't have vimcmdline installed on Windows.

**Comment by adrianadermon** [comment]
It does not solve the issue, unfortunately. All that happens is that two extra blank lines are sent to the REPL (with the default setting, one extra blank line is added beneath the entered expression), but I still have to go there and hit enter to get it to evaluate. 

I also noticed now that Julia also gets an extra line with the default setting, but at least each line is evaluated.

**Comment by jalvesaq** [comment]
I tested it on Windows with "\r\n" as newline and worked. Perhaps it depends on Python version. Anyway, I have just changed the newline on Windows.

**Comment by adrianadermon** [comment]
This works correctly in the Python prompt now, but I get the same problem as before in iPython.

**Comment by jalvesaq** [comment]
It would be better if vimcmdline was compatible with iPython, but iPython is too interactive to be easy to handle. I'm using [ale](https://github.com/w0rp/ale), [jedi](https://github.com/davidhalter/jedi) and  [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) to help me writing Python code. When I need to test a few lines of code, I write them in the script buffer with zero indentation, send the lines to Python, and, then, either fix the indentation or delete the code. More experienced Python developers might have a better workflow.
