### ISSUE TITLE
unknown function chansend

### ISSUE THREAD

**Issue by shuaiwang88** [jalvesaq/vimcmdline#43]
I did a 'apt upgrade' and both my ubuntu 18.04 machine stop to work. 
Showing error:
 ```
"Error detected while processing fuction RonJobStout[7].. SetNvimcomInfo[77]..JobStdin: line 1:
unknown function: chansend"
```

**Comment by jalvesaq** [comment]
Could update your plugins again, please? The issue should be fixed now.

**Comment by shuaiwang88** [comment]
works!

**Comment by jalvesaq** [comment]
Thanks for reporting the issue, and for the feedback. The problem was in Nvim-R...
