### ISSUE TITLE
Matlab and source

### ISSUE THREAD

**Issue by igmmgi** [jalvesaq/vimcmdline#55]
call VimCmdLineSendCmd('source ("' . g:cmdline_tmp_dir . '/lines.m");')

I think source is an Octave only function. The equivalent Matlab function is run.
Changing source to run allows sending multiple lines in Matlab. Without this change it does not work for me.

**Comment by jalvesaq** [comment]
Does the lines below work as a replacement of line 8 of `ftplugin/matlab_cmdline.vim`? Could you try this change, please?

```vim
    if b:cmdline_app == "matlab"
        call VimCmdLineSendCmd('run("' . g:cmdline_tmp_dir . '/lines.m");')
    else
        call VimCmdLineSendCmd('source("' . g:cmdline_tmp_dir . '/lines.m");')
    endif
```

**Comment by igmmgi** [comment]
No. Same issue but I think I see the problem. A matlab terminal instance would be created by calling something like 
matlab -nojvm -nodisplay -nosplash

Might be easier changing the order to check for octave then put the run version in the else? This would work for many combinations ot matlab start commands.

Thanks.

**Comment by jalvesaq** [comment]
I prefer to keep octave as default because it is free software. But this condition should work:

```
    if b:cmdline_app =~? "^matlab"
```

Could you try it, please?

**Comment by igmmgi** [comment]
Yes, that works. Thanks.

**Comment by jalvesaq** [comment]
Thanks!
