### ISSUE TITLE
SendCmdLine error when sending -1

### ISSUE THREAD

**Issue by statquant** [jalvesaq/vimcmdline#6]
I added [kdb](https://kx.com/) support and realize that sending the line "-1" (just the number)
-1
would break the VimCmdLineSendLine function in any filetype
![sendlinebreak](https://cloud.githubusercontent.com/assets/3612473/17649172/a78fb77e-6225-11e6-91de-617d3adf2576.png)

**Comment by jalvesaq** [comment]
I copied the solution from Nvim-R: add a space to the beginning of the line. But at least for Python this may cause problem with indentation. See: https://github.com/jalvesaq/vimcmdline/commit/5f5240a9a52dada22915cb7d12984f8c666306ad
