### ISSUE TITLE
Cannot start interpreter because not inside a Tmux session.

### ISSUE THREAD

**Issue by ZihaoXingstudy** [jalvesaq/vimcmdline#69]
when i open a terminal ,to edit test.py ,when i tap \s, it can't start the interpreter
,when i open tmux ,and edit test.py on tmux , when i tap \s, it also can't start the interpreter

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the issue.

**Comment by ZihaoXingstudy** [comment]
i solved my problem by removed
let cmdline_app           = {}
let cmdline_app['python'] = 'ptipython3'
let cmdline_app['ruby']   = 'pry'
let cmdline_app['sh']     = 'bash'

in  my ~/.vimrc

**Comment by jalvesaq** [comment]
Thanks for the feedback!
