### ISSUE TITLE
can vimcmdline add a perl script language  support ? 

### ISSUE THREAD

**Issue by ZihaoXingstudy** [jalvesaq/vimcmdline#70]
can vimcmdline add a perl script language  support ?  perl is also a very important language same as python and R.

**Comment by jalvesaq** [comment]
Vimcmdline can support any interpreted language, but someone has to write the code and to do a pull request to include it. Please, read the section *How to add support for a new language* in the [README](https://github.com/jalvesaq/vimcmdline/blob/master/README.md).
