### ISSUE TITLE
Issue in neovim terminal but not tmux

### ISSUE THREAD

**Issue by statquant** [jalvesaq/vimcmdline#72]
Hello when I try to use the kdb interpreter in neovim I get the following

![image](https://user-images.githubusercontent.com/3612473/58375840-777a6080-7f54-11e9-847c-ec74f8a80341.png)

![image](https://user-images.githubusercontent.com/3612473/58375853-af81a380-7f54-11e9-8201-2c3c455e8f09.png)
after I press enter line is correctly copied
when I use tmux all is fine

**Comment by jalvesaq** [comment]
@statquant, the support for kdb was added by you. I don't have kdb installed and don't know how to program in the language. So, could you please try to fix the issue and do a pull request?

**Comment by statquant** [comment]
Hello, the thing is that everything work just fine in tmux, so I feel like this is something unrelated with q/kdb

**Comment by statquant** [comment]
it worked fine for me today
