### ISSUE TITLE
Python send paragraph sends extra blanks lines to repl

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/vimcmdline#75]
Windows 10, python 3.7

![image](https://user-images.githubusercontent.com/12205650/62141276-47d03780-b2ba-11e9-8669-845df3a710ee.png)

**Comment by jalvesaq** [comment]
I think an extra blank line might be necessary if, for example, the paragraph is a function definition. I changed the code to add an extra blank line only if the last line is not a blank line yet. Is it OK now?

**Comment by blayz3r** [comment]
Still see it, does the fix work on your machine? I agree, it works the way you expect for a class or function but introduces extra lines for regular paragraphs.

**Comment by jalvesaq** [comment]
I never use the send paragraph function...

Could you, please, try changing the code in `ftplugin/python_cmdline.vim` (line 42) from

```
        if a:lines[len(a:lines)-1] == ''
            call VimCmdLineSendCmd(join(a:lines, b:cmdline_nl))
        else
            call VimCmdLineSendCmd(join(add(a:lines, ''), b:cmdline_nl))
        endif
```

to

```
        call VimCmdLineSendCmd(join(a:lines, b:cmdline_nl))
```
? Does it work?

**Comment by blayz3r** [comment]
Yep better. thanks.

**Comment by blayz3r** [comment]
Using **_:call PythonSourceLines(getline(1,3))_** works fine but it looks like:

https://github.com/jalvesaq/vimcmdline/blob/804b3785441bd4a6559bdfb3ab9e7be8b3cae7bc/plugin/vimcmdline.vim#L320-L330

Adds the empty line before the loop breaks
