### ISSUE TITLE
Would that be possible to have several cmdline_app per filetype and start interpreter differently per repl

### ISSUE THREAD

**Issue by statquant** [jalvesaq/vimcmdline#76]
Hello this is more a question

1. Several cmdline_app per filetype

On some `ft` I'd like to be able to start different interpreters, would that be able to do ?
I was thinking about something like

let cmdline_ft['python-2'] = 'python' " python-2 will use everything python uses
let cmdline_app           = {}
let cmdline_app['python'] = 'ptipython3'
let cmdline_app['python-2'] = 'somestuff'

2. Can we start interpreter differently per repl (I guess that equivalent of cmdline_app for cmdline_map_start)

Kind regards

**Comment by jalvesaq** [comment]
The filetype is defined by Vim/Neovim, and there is only one file type for Python, as you can see at either Vim' s or Neovim's ftplugin directory, for example, '/usr/share/vim/vim81/ftplugin/`

You could use an `autocmd` to change the value of `cmdline_app['python']` according to your needs.

**Comment by statquant** [comment]
Ok actually I forgot that I can give any command to `cmdline_app` so I have created a bash script that does what I want and fed this to `cmdline_app`.
On a tangential topic, I want to be able to send a file to the interpreter, in `kdb` the command would be `\l <the file>` while in R that would be `source("<the file>")`, I had something before but while pulling the newest code it does not work anymore. Can I do this easily ?

**Comment by jalvesaq** [comment]
Perhaps you could use ftplugin/sh_cmdline.vim as an example, and maybe this works:

```vim
function! KbdSourceLines(lines)
    call writefile(a:lines, g:cmdline_tmp_dir . '/lines.q')
    call VimCmdLineSendCmd('\\ ' . g:cmdline_tmp_dir . '/lines.q')
endfunction

let b:cmdline_source_fun = function('KbdSourceLines')
```

**Comment by jalvesaq** [comment]
I just noted that the function already exists, but I don't have kdb installed to try it.

**Comment by statquant** [comment]
Ok the following solved it for me, I am so bad at scripting vim it is embarrassing...
```
autocmd FileType kdb nnoremap <buffer> <LocalLeader>aa :call VimCmdLineSendCmd("\\l " . expand('%:p'))<CR>
autocmd FileType kdb inoremap <buffer> <LocalLeader>aa :call VimCmdLineSendCmd("\\l " . expand('%:p'))<CR>
```

**Comment by statquant** [comment]
Actually there is another issue.
When I visual select several lines I now get the following error

```
Error detected while processing /lxhome/statquant/.local/share/nvim/plugged/vimcmdline/ftplugin/kdb_cmdline.vim:   
line   10:                                                                                                        
E127: Cannot redefine function KdbSourceLines: It is in use                                                       
Press ENTER or type command to continue    
```                                                                       
In the terminal the temp file is correctly sourced
`q)\l /tmp/cmdline_1569245558_statquant/lines.q`
and the content of the file itself is also fine ie. when I execute the same command it works fine.
I am not sure what is the problem with "redefining" ?

EDIT:
It seems I get the same error for any block/paragraph mapping
my initrc is as follows

```
"============                                                                                         
" vimcmdline                                                                                          
"============                                                                                         
                                                                                                      
" mappings                                                                                            
autocmd BufEnter *.q :set filetype=kdb                                                                
let cmdline_map_start = '<LocalLeader>rf'                                                             
let cmdline_map_send = '<Space>'                                                                      
let cmdline_map_send_and_stay = '<LocalLeader><Space>'                                                
let cmdline_map_source_fun = '<LocalLeader>f'                                                         
let cmdline_map_send_paragraph = '<LocalLeader>p'                                                     
let cmdline_map_send_block = '<LocalLeader>b'                                                         
let cmdline_map_quit = '<LocalLeader>rq'                                                              
let cmdline_app = {}                                                                                  
let cmdline_app['kdb'] = '/lxhome/statquant/bin/q.sh 3.6u -s 24 -p 0W'                                 
autocmd FileType kdb nmap <buffer> <LocalLeader>aa :call VimCmdLineSendCmd("\\l " . expand('%:p'))<CR>
autocmd FileType kdb imap <buffer> <LocalLeader>aa :call VimCmdLineSendCmd("\\l " . expand('%:p'))<CR>
```

**Comment by statquant** [comment]
Ok it seems that `autocmd BufEnter *.q :set filetype=kdb` is the culprit.
Removing it works
...
