### ISSUE TITLE
Does vimcmdline supports multiple buffers ?

### ISSUE THREAD

**Issue by statquant** [jalvesaq/vimcmdline#8]
Hello, would that be easy to add multiple buffer support like for vim-r-plugin ?
When I open anyfile in tmux, then get a terminal then open another buffer the second buffer cannot send lines to the console (we can do that in vim-r-plugin)

**Comment by alok** [comment]
+1 to this. This feature may be tricky to implement, but it would _really_ useful.

**Comment by jalvesaq** [comment]
Currently, it is one interpreter instance per buffer. It cannot be one interpreter per Vim instance as in the Nvim-R, but I can change it to be one per file type.
