### ISSUE TITLE
README does not make clear whether Tmux is required

### ISSUE THREAD

**Issue by ekiefl** [jalvesaq/vimcmdline#82]
In Vim, when starting a session I get the error:

"Cannot start interpreter because not inside a Tmux session."

Is Tmux required for this plugin?

**Comment by jalvesaq** [comment]
The README should be clearer now: https://github.com/jalvesaq/vimcmdline/commit/5ba34782fe6cef1eb174ea1d2a9f4ec40ecdfdd1
