### ISSUE TITLE
VIM help for plugin is missed

### ISSUE THREAD

**Issue by petRUShka** [jalvesaq/vimcmdline#91]
Having a comprehensive help pages seems to be VIM/NVIM standard for VIM plugins.

It is also very convenient to have all help in one place and not to switch to browser when you need some information about some particular features.

Please, add VIM help pages.

**Comment by jalvesaq** [comment]
I don't want to maintain two versions of the same document (README.md and doc/vimcmdline.txt). What do you think if I move the sections *Usage* and *Options* to Vim documentation, but keep the introductory section, *How to install* and *How to add support for a new language* in the README.md?

**Comment by petRUShka** [comment]
I'm thinking that you are right one doesn't need _How to install section_ in vimdoc (because plugin is supposed to be installed before you can read help from within vim). But having introduction seems to be useful.

In my opinion _How to add support for a new language_ can be mentioned with link to plugin readme on github.

**Comment by petRUShka** [comment]
I've started some [discussion on the topic](https://vi.stackexchange.com/questions/24877/convert-vim-doc-vim-help-to-markdown-or-vice-versa?noredirect=1#comment43445_24877). I wondered are there tools for converting Markdown to Vim help or vice versa. There is alpha version of such tool but main trend is to consider Vim doc as the main reference and instead use the README as an introduction and/or tutorial.

**Comment by petRUShka** [comment]
I've found another discussion: https://vi.stackexchange.com/questions/3752/how-do-i-generate-vim-documentation-from-markdown-notes-or-inline-comments-or-a

**Comment by jalvesaq** [comment]
I could not make `html2vimdoc.py` work in my system. So, it seems that the best option is to move part of the README contents to `doc/vimcmdline.txt`. I will to this later today or tomorrow.
