### ISSUE TITLE
Does VCL allows me to use ssh?

### ISSUE THREAD

**Issue by roccho-dev** [jalvesaq/vimcmdline#99]
I tried this command.
```
let cmdline_app = {}
let cmdline_app['python'] = 'ssh [mylogin@remote.machine.com](mailto:mylogin@remote.machine.com) python'
```
This command run well.
As image tells us, VCL could connect external session ( ssh )

![image](https://user-images.githubusercontent.com/40359643/156374360-cdfd2eee-aa6b-4614-9e63-2d6c662c8359.png)

but if ssh needs password to enter, vimcmdline seems not to allow me enter it
**VCM allows me to do these?**
1, to use ssh public key connection? if ok, we don't need password
2, to enter password to .vimrc or init.vim? if ok, we don't have to enter it manually, but danger to security
3, to prepare making neovim's terminal mode be logged in already? as write next, I tried preparing neovim's terminal logged in before start vimcmdline, but it seems to be not good

What I want is to connect ssh session because ssh session has good machine resource.
But I don't want to run NeoVim in ssh because of overhead.
I want to run neovim ( session A, I'm here ) and want only to send code to ssh ( external session B ) for talking with interpreter .
So, I'm happy if VCL can send codes unit|block to external session like ssh.

**Comment by jalvesaq** [comment]
I have never seriously used ssh, but, as far as I know, public key authentication is considered more secure and convenient than password authentication.

**Comment by roccho-dev** [comment]
Hi, thanks for your reply.
Do you mean that VCL will not require me if I already set ssh key pair to both host | server and client ( session A, this terminal )?

**Comment by jalvesaq** [comment]
I guess so. But, I have no experience with ssh public key authentication. I don't know how you should configure your systems.
